
Schema.voices.Add("PASystem", "CODE RED", "All units are now on Code Red. Repeat: Code Red conditions are in-effect.", "redfactionrp/voices/pa/coderedineffect.wav", true)
Schema.voices.Add("PASystem", "DISTURBANCE C2", "Code Yellow alert. Disturbance in Barracks C2. Security, respond.", "redfactionrp/voices/pa/disturbancec2.wav", true)
Schema.voices.Add("PASystem", "DISTURBANCE M4", "Disturbance in Mine Sector M4. Code Yellow alert.", "redfactionrp/voices/pa/disturbanceinm4.wav", true)
Schema.voices.Add("PASystem", "EMERGENCY C2", "Code Red Alert. Security emergency in Barracks C2. All available personnel, respond.", "redfactionrp/voices/pa/emergencyc2.wav", true)
Schema.voices.Add("PASystem", "EMERGENCY M4", "Code Red Emergency in Mine M4. Security Level 1 response required.", "redfactionrp/voices/pa/lvl1responsem4.wav", true)
Schema.voices.Add("PASystem", "RED ALERT M4", "Code Red Alert in Mine M4. Security Level 2 response required.", "redfactionrp/voices/pa/lvl2responsem4.wav", true)
Schema.voices.Add("PASystem", "INTRUDER ALERT", "Intruder Alert. Sector Lockdown in-effect. Code Red Emergency.", "redfactionrp/voices/pa/sectorlockdownintruder.wav", true)
Schema.voices.Add("PASystem", "INTRUDER IN GUARD FACILITY", "Intruder in Guard Training Facility. Security response required.", "redfactionrp/voices/pa/intruderintrainingfacility.wav", true)
Schema.voices.Add("PASystem", "M4 SEAL IN FIVE MIN", "Attention all personnel. Mine M4 will be sealed in 5 minutes. All personnel are required to evacuate immediately.", "redfactionrp/voices/pa/m4seal5min.wav", true)
Schema.voices.Add("PASystem", "M4 SEALED", "Attention all personnel. Mine M4 has been sealed.", "redfactionrp/voices/pa/m4sealed.wav", true)
Schema.voices.Add("PASystem", "MINERS LAY DOWN WEAPONS", "All miners are ordered to lay down their weapons, and report to the nearest Security Checkpoint. You will not be harmed.", "redfactionrp/voices/pa/minerslaydownweapons.wav", true)
Schema.voices.Add("PASystem", "MINERS RETURN TO BARRACKS", "All miners are required to return to their barracks until further notice.", "redfactionrp/voices/pa/minersreturnbarracks.wav", true)
Schema.voices.Add("PASystem", "MINERS TO GUARD STATION", "All miners report to the nearest guard station. You will not be harmed.", "redfactionrp/voices/pa/minerstoguardstation.wav", true)
Schema.voices.Add("PASystem", "SECURITY TO C2", "Security to Miner Barracks C2. Security to Barracks C2.", "redfactionrp/voices/pa/securitytoc2.wav", true)
Schema.voices.Add("PASystem", "MORE SECURITY TO C2", "Additional security needed in Miner Barracks C2.", "redfactionrp/voices/pa/moresecuritytoc2.wav", true)
Schema.voices.Add("PASystem", "NON SECURITY RETURN TO BARRACKS", "All Non-Security personnel are required to return to their barracks for the duration of the disturbances.", "redfactionrp/voices/pa/nonsecurityreturntobarracks.wav", true)
Schema.voices.Add("PASystem", "SECOND WORKSHIFT ENDED", "Second Work-Shift has ended. Miners return to barracks.", "redfactionrp/voices/pa/secondworkshiftended.wav", true)
Schema.voices.Add("PASystem", "MORE SECURITY TO M4", "Additional security required in Mine Sector M4.", "redfactionrp/voices/pa/securitytom4.wav", true)
Schema.voices.Add("PASystem", "RED ALERT MORE SECURITY TO M4", "Code Red Alert. Additional security required in Mine Sector M4.", "redfactionrp/voices/pa/securitytom4redalert.wav", true)
Schema.voices.Add("PASystem", "UNAUTHORIZED VEHICLE USAGE", "Unauthorized vehicle usage in M4 Driller Bay. Security, respond.", "redfactionrp/voices/pa/vehicleusagem4.wav", true)

Schema.voices.Add("Guard", "ANOTHER ONE GET HIM", "There's another one, get him!", "redfactionrp/voices/guard/anotheronegethim.wav")
Schema.voices.Add("Guard", "ATTACK ATTACK", "Attack, attack!", "redfactionrp/voices/guard/attackattack.wav")
Schema.voices.Add("Guard", "BETTER RUN MINER", "Better run, miner!", "redfactionrp/voices/guard/betterrunminer.wav")
Schema.voices.Add("Guard", "COME ON", "Come on!", "redfactionrp/voices/guard/comeon.wav")
Schema.voices.Add("Guard", "COME ON TOUGH GUY", "Come on, tough guy.", "redfactionrp/voices/guard/comeontoughguy.wav")
Schema.voices.Add("Guard", "COVER ME", "Cover me!", "redfactionrp/voices/guard/coverme.wav")
Schema.voices.Add("Guard", "DAMN MINERS", "Damn miners.", "redfactionrp/voices/guard/damnminers.wav")
Schema.voices.Add("Guard", "DIE MINER", "Die, miner!", "redfactionrp/voices/guard/dieminer.wav")
Schema.voices.Add("Guard", "DIE SCUM", "Die, scum!", "redfactionrp/voices/guard/diescum.wav")
Schema.voices.Add("Guard", "DON'T DO IT PLEASE", "Don't do it, please!", "redfactionrp/voices/guard/dontdoitplease.wav")
Schema.voices.Add("Guard", "DROP YOUR WEAPONS", "Drop your weapons!", "redfactionrp/voices/guard/dropyourweapons.wav")
Schema.voices.Add("Guard", "FOLLOW ME", "Follow me!", "redfactionrp/voices/guard/followme.wav")
Schema.voices.Add("Guard", "GET HIM", "Get him!", "redfactionrp/voices/guard/gethim.wav")
Schema.voices.Add("Guard", "GET OVER HERE", "Get over here!", "redfactionrp/voices/guard/getoverhere.wav")
Schema.voices.Add("Guard", "GIVE UP MINER", "Give up, miner.", "redfactionrp/voices/guard/giveupminer.wav")
Schema.voices.Add("Guard", "GO GO GO", "Go, go, go!", "redfactionrp/voices/guard/gogogo.wav")
Schema.voices.Add("Guard", "HALT", "Halt!", "redfactionrp/voices/guard/halt.wav")
Schema.voices.Add("Guard", "HEADS UP", "Heads up!", "redfactionrp/voices/guard/headsup.wav")
Schema.voices.Add("Guard", "HELP HELP", "Help, help!", "redfactionrp/voices/guard/helphelp.wav")
Schema.voices.Add("Guard", "WENT THIS WAY", "He went this way!", "redfactionrp/voices/guard/hewentthisway.wav")
Schema.voices.Add("Guard", "HEY", "Hey!", "redfactionrp/voices/guard/hey.wav")
Schema.voices.Add("Guard", "HOLD IT MINER", "Hold it, miner!", "redfactionrp/voices/guard/holditminer.wav")
Schema.voices.Add("Guard", "DESERVE TO DIE", "I don't deserve to die!", "redfactionrp/voices/guard/idontdeservetodie.wav")
Schema.voices.Add("Guard", "I'M ON YOUR SIDE", "I'm on your side!", "redfactionrp/voices/guard/imonyourside.wav")
Schema.voices.Add("Guard", "I'M SORRY", "I'm sorry... really, really sorry.", "redfactionrp/voices/guard/imsorryreallysorry.wav")
Schema.voices.Add("Guard", "I'M UNARMED", "Don't shoot, I'm unarmed!", "redfactionrp/voices/guard/imunarmed.wav")
Schema.voices.Add("Guard", "JOIN RED FACTION", "I'll join the Red Faction, I promise.", "redfactionrp/voices/guard/joinredfaction.wav")
Schema.voices.Add("Guard", "JUST FOLLOWING ORDERS", "I was just following orders.", "redfactionrp/voices/guard/justfollowingorders.wav")
Schema.voices.Add("Guard", "YOU AND ME MINER", "Just you and me, miner.", "redfactionrp/voices/guard/justyouandmeminer.wav")
Schema.voices.Add("Guard", "LET'S GET HIM", "Let's get him!", "redfactionrp/voices/guard/letsgethim.wav")
Schema.voices.Add("Guard", "MERCY PLEASE", "Mercy, please!", "redfactionrp/voices/guard/mercyplease.wav")
Schema.voices.Add("Guard", "MOVE IN", "Move in!", "redfactionrp/voices/guard/movein.wav")
Schema.voices.Add("Guard", "NEED HELP HERE", "Need help here.", "redfactionrp/voices/guard/needhelphere.wav")
Schema.voices.Add("Guard", "ONE FEWER OF YOU RATS", "There'll be one fewer of you rats when I'm done.", "redfactionrp/voices/guard/onefewerofyourats.wav")
Schema.voices.Add("Guard", "ONLY DOING MY JOB", "I was only doing my job.", "redfactionrp/voices/guard/onlydoingmyjob.wav")
Schema.voices.Add("Guard", "PARTY TIME", "Party time.", "redfactionrp/voices/guard/partytime.wav")
Schema.voices.Add("Guard", "SARGE YOU THERE", "Sarge? You there, Sarge?", "redfactionrp/voices/guard/sargeyouthere.wav")
Schema.voices.Add("Guard", "SCUM", "Scum.", "redfactionrp/voices/guard/scum.wav")
Schema.voices.Add("Guard", "STOP", "Stop.", "redfactionrp/voices/guard/stop.wav")
Schema.voices.Add("Guard", "STOP RIGHT THERE", "Stop right there!", "redfactionrp/voices/guard/stoprightthere.wav")
Schema.voices.Add("Guard", "TOO LATE FOR THAT", "Too late for that, mine-scum.", "redfactionrp/voices/guard/toolateminescum.wav")
Schema.voices.Add("Guard", "TRY IT MINER", "Try it, miner.", "redfactionrp/voices/guard/tryitminer.wav")
Schema.voices.Add("Guard", "ULTOR SUCKS", "Ultor sucks... don't shoot me!", "redfactionrp/voices/guard/ultorsucks.wav")
Schema.voices.Add("Guard", "WHERE'S MY BACKUP", "Where's my backup?!", "redfactionrp/voices/guard/wheresmybackup.wav")
Schema.voices.Add("Guard", "WHERE YOU GOING", "Hey, where do you think you're going?", "redfactionrp/voices/guard/whereyougoing.wav")
Schema.voices.Add("Guard", "WHO'S DOWN THERE", "Who's down there?! Throw down your weapons, and come out!", "redfactionrp/voices/guard/whosdownthere.wav")
Schema.voices.Add("Guard", "WHO'S THERE SHOW YOURSELF", "Who's there? Show yourself, hands in the air!", "redfactionrp/voices/guard/whosthereshowyourself.wav")
Schema.voices.Add("Guard", "YOU LOOKING AT", "What are you looking at, miners?", "redfactionrp/voices/guard/youlookingat.wav")
Schema.voices.Add("Guard", "YOU'RE DEAD TRAITOR", "You're dead, traitor.", "redfactionrp/voices/guard/youredeadtraitor.wav")
Schema.voices.Add("Guard", "YOU'RE HEARING THINGS", "You're hearing things.", "redfactionrp/voices/guard/yourehearingthings.wav")

Schema.voices.Add("GuardCommander", "ATTACK", "Attack!", "redfactionrp/voices/guardcommander/attack.wav")
Schema.voices.Add("GuardCommander", "BUSTED MINERAT", "Busted, mine-rat!", "redfactionrp/voices/guardcommander/bustedminerat.wav")
Schema.voices.Add("GuardCommander", "COME GET SOME", "Come get some!", "redfactionrp/voices/guardcommander/comegetsome.wav")
Schema.voices.Add("GuardCommander", "FLANK HIM", "Flank him!", "redfactionrp/voices/guardcommander/flankhim.wav")
Schema.voices.Add("GuardCommander", "GAME'S OVER SCUM", "Game's over, scum!", "redfactionrp/voices/guardcommander/gamesoverscum.wav")
Schema.voices.Add("GuardCommander", "GO GO GO", "Go, go, go!", "redfactionrp/voices/guardcommander/gogogo.wav")
Schema.voices.Add("GuardCommander", "HEADS UP", "Heads up!", "redfactionrp/voices/guardcommander/headsup.wav")
Schema.voices.Add("GuardCommander", "STOP RIGHT THERE", "Stop right there!", "redfactionrp/voices/guardcommander/heyyoustoprightthere.wav")
Schema.voices.Add("GuardCommander", "HIT EM HARD", "Hit 'em hard!", "redfactionrp/voices/guardcommander/hitemhard.wav")
Schema.voices.Add("GuardCommander", "HOLD IT LOWLIFE", "Hold it, lowlife.", "redfactionrp/voices/guardcommander/holditlowlife.wav")
Schema.voices.Add("GuardCommander", "DIDN'T ASK FOR PROMOTION", "I didn't ask for this promotion.", "redfactionrp/voices/guardcommander/ididntaskforthispromotion.wav")
Schema.voices.Add("GuardCommander", "I GIVE UP", "I give up.", "redfactionrp/voices/guardcommander/igiveup.wav")
Schema.voices.Add("GuardCommander", "I'M A MINER UNDERCOVER", "I'm really a miner, undercover.", "redfactionrp/voices/guardcommander/imreallyaminerundercover.wav")
Schema.voices.Add("GuardCommander", "I SURRENDER", "I surrender!", "redfactionrp/voices/guardcommander/isurrender.wav")
Schema.voices.Add("GuardCommander", "LET ME LIVE WON'T SHOOT", "Let me live... and I'll never shoot another miner, I promise!", "redfactionrp/voices/guardcommander/letmeliveillnevershoot.wav")
Schema.voices.Add("GuardCommander", "LET'S GO GET DOWN HERE", "Let's go, get your butts down here!", "redfactionrp/voices/guardcommander/letsgogetdownhere.wav")
Schema.voices.Add("GuardCommander", "LET'S GO LET'S GO", "Let's go, let's go!", "redfactionrp/voices/guardcommander/letsgoletsgo.wav")
Schema.voices.Add("GuardCommander", "I HATE MARS", "Man, I hate Mars.", "redfactionrp/voices/guardcommander/manihatemars.wav")
Schema.voices.Add("GuardCommander", "MOVE IT", "Move it!", "redfactionrp/voices/guardcommander/moveit.wav")
Schema.voices.Add("GuardCommander", "NO DONT", "No, don't!", "redfactionrp/voices/guardcommander/nodont.wav")
Schema.voices.Add("GuardCommander", "NO MERCY", "No mercy.", "redfactionrp/voices/guardcommander/nomercy.wav")
Schema.voices.Add("GuardCommander", "PAYBACK TIME", "Payback time!", "redfactionrp/voices/guardcommander/paybacktime.wav")
Schema.voices.Add("GuardCommander", "PREPARE TO DIE", "Prepare to die!", "redfactionrp/voices/guardcommander/preparetodie.wav")
Schema.voices.Add("GuardCommander", "PROTEST THIS MINER", "Protest this, miner!", "redfactionrp/voices/guardcommander/protestthisminer.wav")
Schema.voices.Add("GuardCommander", "REBEL SCUM", "Rebel scum!", "redfactionrp/voices/guardcommander/rebelscum.wav")
Schema.voices.Add("GuardCommander", "SAY YOUR PRAYERS", "Say your prayers, miner!", "redfactionrp/voices/guardcommander/sayyourprayersminer.wav")
Schema.voices.Add("GuardCommander", "SCUM", "Scum!", "redfactionrp/voices/guardcommander/scum.wav")
Schema.voices.Add("GuardCommander", "STAND STILL AND DIE", "Stand still and die like a man!", "redfactionrp/voices/guardcommander/standstillanddie.wav")
Schema.voices.Add("GuardCommander", "STAY TOGETHER", "Stay together!", "redfactionrp/voices/guardcommander/staytogether.wav")
Schema.voices.Add("GuardCommander", "SURRENDER OR DIE", "Surrender or die!", "redfactionrp/voices/guardcommander/surrenderordie.wav")
Schema.voices.Add("GuardCommander", "TAKE POINT", "Take point.", "redfactionrp/voices/guardcommander/takepoint.wav")
Schema.voices.Add("GuardCommander", "TIME TO DIE MINER", "Time to die, miner!", "redfactionrp/voices/guardcommander/timetodieminer.wav")
Schema.voices.Add("GuardCommander", "TRAITOR", "Traitor!", "redfactionrp/voices/guardcommander/traitor.wav")
Schema.voices.Add("GuardCommander", "TRY AND TAKE ME", "Try and take me, miner.", "redfactionrp/voices/guardcommander/tryandtakememiner.wav")
Schema.voices.Add("GuardCommander", "I HAVE A FAMILY", "Wait... I have a family on Earth!", "redfactionrp/voices/guardcommander/waitihaveafamily.wav")
Schema.voices.Add("GuardCommander", "WATCH THE FLANKS", "Watch the flanks!", "redfactionrp/voices/guardcommander/watchtheflanks.wav")
Schema.voices.Add("GuardCommander", "SHOW YOURSELF", "Who's there? Drop your weapon, and show yourself!", "redfactionrp/voices/guardcommander/whosthereshowyourself.wav")
Schema.voices.Add("GuardCommander", "YOU'RE A DEAD MAN", "You're a dead man!", "redfactionrp/voices/guardcommander/youreadeadman.wav")
Schema.voices.Add("GuardCommander", "YOU'RE GONNA DIE MINER", "You're gonna die, miner!", "redfactionrp/voices/guardcommander/youregonnadieminer.wav")
Schema.voices.Add("GuardCommander", "YOU'RE TERMINATED MINER", "You're terminated, miner!", "redfactionrp/voices/guardcommander/youreterminatedminer.wav")
Schema.voices.Add("GuardCommander", "YOU WIN YOU WIN", "You win, you win!", "redfactionrp/voices/guardcommander/youwinyouwin.wav")

Schema.voices.Add("Miner", "ABOUT TIME YOU GOT HERE", "About time you got here.", "redfactionrp/voices/miner/abouttimeyougot.wav")
Schema.voices.Add("Miner", "AMBUSH", "Ambish!", "redfactionrp/voices/miner/ambush.wav")
Schema.voices.Add("Miner", "ATTACK ATTACK", "Attack, attack!", "redfactionrp/voices/miner/attackattack.wav")
Schema.voices.Add("Miner", "DAMN GUARDS I HATE THEM", "Damn guards, I hate 'em, I hate'em, I hate 'em!", "redfactionrp/voices/miner/damnguardsihatethem.wav")
Schema.voices.Add("Miner", "DON'T HURT ME PLEASE", "Don't hurt me, please!", "redfactionrp/voices/miner/donthurtmeplease.wav")
Schema.voices.Add("Miner", "DON'T SHOOT I GIVE UP", "Don't shoot, I give up.", "redfactionrp/voices/miner/dontshootigiveup.wav")
Schema.voices.Add("Miner", "FREEDOM", "Freedom!", "redfactionrp/voices/miner/freedom.wav")
Schema.voices.Add("Miner", "GLAD YOU COULD MAKE IT", "Glad you could make it.", "redfactionrp/voices/miner/gladyoumakeit.wav")
Schema.voices.Add("Miner", "GO AWAY HIDE", "Go away, find someplace else to hide!", "redfactionrp/voices/miner/goawayhide.wav")
Schema.voices.Add("Miner", "GRAB THAT GUARD'S GUN", "Grab that guard's gun if you need one. He sure doesn't.", "redfactionrp/voices/miner/grabthatguardsgun.wav")
Schema.voices.Add("Miner", "BEFORE GUARDS CATCH UP", "Come on, before those guards catch up!", "redfactionrp/voices/miner/guardscatchup.wav")
Schema.voices.Add("Miner", "HELP HELP", "Help, help!", "redfactionrp/voices/miner/helphelp.wav")
Schema.voices.Add("Miner", "HELP HELP2", "Help, help!", "redfactionrp/voices/miner/helphelp2.wav")
Schema.voices.Add("Miner", "HELP CAN ANYONE HEAR", "Help, help! Can anyone hear me? Help!", "redfactionrp/voices/miner/helphelpcananyonehear.wav")
Schema.voices.Add("Miner", "PLEASE HELP ME", "Help, someone! Please help me!", "redfactionrp/voices/miner/helpsomeonepleasehelp.wav")
Schema.voices.Add("Miner", "YOU AWAKE OVER THERE", "Hey buddy. You awake over there?", "redfactionrp/voices/miner/heybuddyyouawake.wav")
Schema.voices.Add("Miner", "WE'RE WITH THE RED FACTION", "Hey, get over here. We're with the Red Faction.", "redfactionrp/voices/miner/heygetoverhere.wav")
Schema.voices.Add("Miner", "CAN'T HELP YOU", "I'm sorry, I can't help you.", "redfactionrp/voices/miner/icanthelpyou.wav")
Schema.voices.Add("Miner", "DID ASK FOR ADVENTURE", "Well, I did ask for adventure.", "redfactionrp/voices/miner/ididaskforadventure.wav")
Schema.voices.Add("Miner", "I HAVE MY ORDERS", "I have my orders.", "redfactionrp/voices/miner/ihavemyorders.wav")
Schema.voices.Add("Miner", "I HOPE WE WIN", "I hope we win.", "redfactionrp/voices/miner/ihopewewin.wav")
Schema.voices.Add("Miner", "I'LL GO BACK TO WORK", "I'll go back to work, I promise.", "redfactionrp/voices/miner/illgobacktowork.wav")
Schema.voices.Add("Miner", "HOLD THIS POSITION", "I'll stay here and hold this position.", "redfactionrp/voices/miner/illstayhereandhold.wav")
Schema.voices.Add("Miner", "I'M A PEACEFUL MAN", "I'm a peaceful man.", "redfactionrp/voices/miner/imapeacefulman.wav")
Schema.voices.Add("Miner", "IT'S ABOUT TIME", "It's about time.", "redfactionrp/voices/miner/itsabouttime.wav")
Schema.voices.Add("Miner", "QUIET OUT THERE", "It's quiet out there... too quiet.", "redfactionrp/voices/miner/itsquiettooquiet.wav")
Schema.voices.Add("Miner", "SUPPOSE I'LL BE LOOKING FOR A JOB", "I suppose I'll be looking for a new job, soon.", "redfactionrp/voices/miner/lookingforanewjob.wav")
Schema.voices.Add("Miner", "MAKE EVERY SHOT COUNT", "Make every shot count!", "redfactionrp/voices/miner/makeeveryshotcount.wav")
Schema.voices.Add("Miner", "MAYBE WE GIVE UP", "Maybe we should just give up.", "redfactionrp/voices/miner/maybewegiveup.wav")
Schema.voices.Add("Miner", "MOVING TO THE ASTEROID BELT", "If I survive this, I'm moving to the asteroid belt.", "redfactionrp/voices/miner/movinttotheasteroidbelt.wav")
Schema.voices.Add("Miner", "MY ORDERS ARE TO STAY HERE", "My orders are to stay here.", "redfactionrp/voices/miner/myordersaretostayhere.wav")
Schema.voices.Add("Miner", "STOP PLEASE I'LL WORK", "No, stop, please! I'll go back to work!", "redfactionrp/voices/miner/nostopplease.wav")
Schema.voices.Add("Miner", "PLEASE DON'T SHOOT", "Please don't shoot.", "redfactionrp/voices/miner/pleasedontshoot.wav")
Schema.voices.Add("Miner", "PLEASE LET ME LIVE", "Please, let me live!", "redfactionrp/voices/miner/pleaseletmelive.wav")
Schema.voices.Add("Miner", "RED FACTION", "Red Faction!", "redfactionrp/voices/miner/redfaction.wav")
Schema.voices.Add("Miner", "RED FACTION2", "Red Faction!", "redfactionrp/voices/miner/redfaction2.wav")
Schema.voices.Add("Miner", "RED FACTION3", "Red Faction!", "redfactionrp/voices/miner/redfaction3.wav")
Schema.voices.Add("Miner", "RED FACTION4", "Red Faction!", "redfactionrp/voices/miner/redfaction4.wav")
Schema.voices.Add("Miner", "RED FACTION5", "Red Faction!", "redfactionrp/voices/miner/redfaction5.wav")
Schema.voices.Add("Miner", "REINFORCEMENTS", "Reinforcements!", "redfactionrp/voices/miner/reinforcements.wav")
Schema.voices.Add("Miner", "THEY'RE KILLING EVERYONE", "Run! They're killing everyone in the barracks!", "redfactionrp/voices/miner/runtheyrekillingeveryone.wav")
Schema.voices.Add("Miner", "STAY TOGETHER", "Stay together!", "redfactionrp/voices/miner/staytogether.wav")
Schema.voices.Add("Miner", "STICK WITH US", "Stick with us, we're heading to the Red Faction base.", "redfactionrp/voices/miner/stickwithus.wav")
Schema.voices.Add("Miner", "STOP I SURRENDER", "Stop, please! I surrender.", "redfactionrp/voices/miner/stoppleaseisurrender.wav")
Schema.voices.Add("Miner", "THANKS COME WITH ME", "Thanks. Hey, come with me.", "redfactionrp/voices/miner/thankscomewithme.wav")
Schema.voices.Add("Miner", "THANKS FOLLOW ME", "Thanks. Follow me!", "redfactionrp/voices/miner/thanksfollowme.wav")
Schema.voices.Add("Miner", "WATCH YOUR BACKS", "Watch your backs, miners!", "redfactionrp/voices/miner/watchyourbacks.wav")
Schema.voices.Add("Miner", "WE'RE PINNED DOWN", "We're pinned down.", "redfactionrp/voices/miner/werepinneddown.wav")
Schema.voices.Add("Miner", "WORK TOGETHER MINERS", "Work together, miners!", "redfactionrp/voices/miner/worktogether.wav")
Schema.voices.Add("Miner", "YOU GO AHEAD", "You go ahead.", "redfactionrp/voices/miner/yougoahead.wav")

Schema.voices.Add("Shared", "HUM", "*Humming*", "redfactionrp/voices/hum01.wav")
Schema.voices.Add("Shared", "HUM2", "*Humming*", "redfactionrp/voices/hum02.wav")
Schema.voices.Add("Shared", "HUM3", "*Humming*", "redfactionrp/voices/hum03.wav")
Schema.voices.Add("Shared", "HUM4", "*Humming*", "redfactionrp/voices/hum04.wav")
Schema.voices.Add("Shared", "HUM5", "*Humming*", "redfactionrp/voices/hum05.wav")
Schema.voices.Add("Shared", "HUM6", "*Humming*", "redfactionrp/voices/hum06.wav")

Schema.voices.AddClass("PASystem", function(client)
	return client:Team() == FACTION_GUARD and Schema:IsRank(client, "CmD")
end)

Schema.voices.AddClass("Guard", function(client)
	return client:Team() == FACTION_GUARD and !Schema:IsRank(client, "CmD")
end)

Schema.voices.AddClass("GuardCommander", function(client)
	return client:Team() == FACTION_GUARD and Schema:IsRank(client, "CmD")
end)

Schema.voices.AddClass("Miner", function(client)
	return client:Team() == FACTION_MINER
end)

Schema.voices.AddClass("Shared", function(client) return true end)
